from __future__ import annotations


class KberifError(Exception):
    def __init__(self, code: str, message: str):
        super().__init__(message)
        self.code = code
        self.message = message

    def to_dict(self) -> dict:
        return {"error": {"code": self.code, "message": self.message}}


KIND_MISMATCH = "KIND_MISMATCH"
TOPIC_NOT_FOUND = "TOPIC_NOT_FOUND"
CARD_ID_MISMATCH = "CARD_ID_MISMATCH"
CARD_SCHEMA_INVALID = "CARD_SCHEMA_INVALID"
CARD_REQUIRED_MISSING = "CARD_REQUIRED_MISSING"
EVIDENCE_PATH_NOT_IN_MANIFEST = "EVIDENCE_PATH_NOT_IN_MANIFEST"
EVIDENCE_LINE_RANGE_INVALID = "EVIDENCE_LINE_RANGE_INVALID"
DENY_PATH_REFERENCED = "DENY_PATH_REFERENCED"
WRITE_DISABLED = "WRITE_DISABLED"
RUNTIME_AI_DISABLED = "RUNTIME_AI_DISABLED"
MANIFEST_MISSING = "MANIFEST_MISSING"
CARDS_CATALOG_INVALID = "CARDS_CATALOG_INVALID"
ITEM_COUNT_MISMATCH = "ITEM_COUNT_MISMATCH"
DETAIL_REQUIRED_MISSING = "DETAIL_REQUIRED_MISSING"
DETAIL_SCHEMA_INVALID = "DETAIL_SCHEMA_INVALID"
DETAIL_CARD_MISMATCH = "DETAIL_CARD_MISMATCH"
DETAIL_SECTION_MISSING = "DETAIL_SECTION_MISSING"
DETAIL_METADATA_MISMATCH = "DETAIL_METADATA_MISMATCH"
VALIDATION_FAILED = "VALIDATION_FAILED"
